### ISSUE TITLE
npm install not working (couldn't read dependencies)

### ISSUE THREAD

**Issue by cjroebuck** [Morriz/backbone-everywhere#1]
Package.json is broken?

`backbone-everywhere git:(master) npm install
npm ERR! Couldn't read dependencies.
npm ERR! Failed to parse json
npm ERR! Unexpected string
npm ERR! File: /Users/cjroebuck/Dev/backbone-everywhere/package.json
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
npm ERR! JSON.parse 
npm ERR! JSON.parse This is not a bug in npm.
npm ERR! JSON.parse Tell the package author to fix their package.json file.
npm ERR! 
npm ERR! System Darwin 11.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/cjroebuck/Dev/backbone-everywhere
npm ERR! node -v v0.4.10
npm ERR! npm -v 1.0.24
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/cjroebuck/Dev/backbone-everywhere/npm-debug.log
npm not ok`

**Comment by cjroebuck** [comment]
looks like you're just missing a few commas, replace dependencies / keywords with:

```
"dependencies"  : {
  "underscore": "",
  "express": "",
  "connect-gzip": "",
  "redis": "",
  "socket.io":"",
  "jsdom": ""
},
"keywords" : [
  "jquery",
  "jsdom",
  "backbone", 
  "redis",
  "socket.io",
  "pubsub", 
  "socket",
  "pushState"
],
```

**Comment by Morriz** [comment]
It is not an installable package...

---

**Comment by cjroebuck** [comment]
understood, but it just makes it easier for people to clone it, install dependencies and run it locally to demo it.
