### ISSUE TITLE
Collections not rendering

### ISSUE THREAD

**Issue by cjroebuck** [Morriz/backbone-everywhere#2]
I run the demo app, enter a few songs and tracks, then click the songs/tracks links at the top, the songs/tracks are not rendering in the collection view, but they are being persisted as I can see the json being passed back with my song titles etc, also if I type in songs/1 in the url, then I get shown the song with id=1

Perhaps the 'reset' event of the collection is not being reacted to on the server, so that the html sent back is 'pre' the reset event is reacted to?

**Comment by Morriz** [comment]
If I am not mistaken, all the models and collections are subscribed to server updates, so you should see the list updated.

I had it working that way just before I committed the last version.

## Mind you that the top links will only work for songs and tracks.

**Comment by Morriz** [comment]
If you update to the latest version, server updates are being propagated.
