### ISSUE TITLE
Can't get it to work with normal Backbone.sync method :(

### ISSUE THREAD

**Issue by cjroebuck** [Morriz/backbone-everywhere#3]
Hey Morriz, thanks a lot for your backbone-everywhere code, I have been trying to get it working on an app this weekend but using the default Backbone.sync, so eventually using $.ajax when requesting data. 

There seems to be an incompatibility with using jsdom and node-jquery together, as im getting the following error when fetching a collection:

500 ReferenceError: status is not defined
at Function.ajax (/.../node_modules/jquery/dist/node-jquery.js:7365:17)

If you want to recreate the same error in your app, just make a call to $.ajax somewhere in one of your routers.

I suspect that somewhere 'this' is being rescoped on the ajax success/error callback but I'm not totally sure. Please if you have time could you help me out as im sure a lot of other people would benefit from having the default Backbone.sync method working with your method.

Thanks
Chris

**Comment by cjroebuck** [comment]
Update: Just found someone with the same issue on the jsdom google group:

https://groups.google.com/group/jsdom/browse_thread/thread/cc761b38bb0f95a/ee9bed7f7f02d2b4?hl=en&lnk=gst&q=xhr#ee9bed7f7f02d2b4

Looks like its an issue with jsdom not supporting all of the xhr object at the moment.

**Comment by Morriz** [comment]
I don't think it has anything to do with that, since you will only use the XHR approach in the client side sync method.
For the server side you'd still have to implement a different sync method that talks to the storage engine, which is now using my adapted backbone-redis solution which injects the data into redis.

**Comment by cjroebuck** [comment]
Yep, I was trying to simulate the client side ajax behaviour on the
server! Sounds silly I know, now I've changed it so that it just talks
directly to my mongoose/mongodb layer

On 15 Sep 2011, at 11:34, Maurice Faber
reply@reply.github.com
wrote:
