### ISSUE TITLE
Globals and multiple requests/sessions

### ISSUE THREAD

**Issue by cjroebuck** [Morriz/backbone-everywhere#5]
Just wondering how these globals will work when multiple requests come in at the same time. Won't they cause race conditions? Is the global window object created once per session or the very first time _anyone_ hits the server?

**Comment by Morriz** [comment]
I have not taken sessions into account, and the window object is global. So yes, this is unstable.
If you really want to set this up for a multi user environment, you could cache a global window object (that is richly setup to your liking), and set that per user request. Or even store that window object per user session (in a registry). I don't know how much memory that would consume, but it would surely make it a helluvalot faster...

---
