### ISSUE TITLE
Anyway to get rid of getViewFunc()?

### ISSUE THREAD

**Issue by cjroebuck** [Morriz/backbone-everywhere#6]
Hi Morriz, me again ;) 

Is there anyway to get rid of the getViewFunc() from the Backbone code. I know this is needed to send back the modified DOM to the client when its run on the server but wouldn't it be cool if we could listen to some DOM mutation event and be called back once the DOM has finished being modified or perhaps automatically wrap each router handler function with the res.send code, possibly using _.wrap?

**Comment by Morriz** [comment]
Hi CJ, I agree the getViewFunc approach is ugly and unwanted. I never got to polish the product, and thought it more explicit for the demo, so I didn't touch it….but you can!

:)

---
