### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by trungpham** [Morriz/backbone-everywhere#9]
I'm looking for a project that brings Backbone.js to Node.js.
This way, nodejs can use backbone to render any URL and package up the rest of backbone code to the browser for subsequence rendering.

I don't want any fancy feature like socket.io, database ORM. Just use plain backbone as is. Even though backbone might run on node, but it should make external rest api when dealing with data.

If you know of such project, then please let me know.

Thanks.

**Comment by Morriz** [comment]
I don't think it exists, because you have to overcome the lack of performance in the dom emulation on nodejs. But like I pointed out in my intro, it can be overcome for just the pages you wish to cache. Anything else I would let the client render. That covers most seo needs.
